FROM rust:latest AS builder

RUN rustup component add rustfmt clippy

ARG VERSION=dev

WORKDIR /app
COPY . .
ENV MARKDOWN_TO_HTML_VERSION=${VERSION}

# Download released homunc to compile .hom files (detect host arch)
RUN ARCH=$(dpkg --print-architecture) && \
    case "$ARCH" in \
      amd64) HOMUNC_ARCH="x86_64" ;; \
      arm64) HOMUNC_ARCH="aarch64" ;; \
      *) HOMUNC_ARCH="x86_64" ;; \
    esac && \
    wget -q "https://github.com/homun-lang/homun/releases/latest/download/homunc-linux-${HOMUNC_ARCH}" -O /usr/local/bin/homunc \
    && chmod +x /usr/local/bin/homunc \
    || true

RUN cargo fmt -- --check
RUN cargo clippy -- -D warnings
RUN cargo build --release
RUN cargo test --release
