FROM rust:latest AS builder

RUN rustup component add rustfmt clippy

ARG VERSION=dev

WORKDIR /app
COPY . .

RUN cargo fmt -- --check
RUN cargo clippy -- -D warnings
RUN cargo build --release
RUN cargo test --release
