//! markdown-to-html — Markdown → HTML compiler.
//!
//! Core logic lives in `src/*.hom`, compiled to `.rs` at build time by
//! `homunc` (see `build.rs`). This file wires the generated code together and
//! exposes the public `convert()` entry point.
#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unused_macros,
    unused_assignments
)]
#![allow(non_snake_case)]
#![allow(
    clippy::clone_on_copy,
    clippy::redundant_field_names,
    clippy::assign_op_pattern,
    clippy::no_effect,
    clippy::unused_unit,
    clippy::needless_return,
    clippy::collapsible_if,
    clippy::collapsible_else_if,
    clippy::ptr_arg,
    clippy::comparison_to_empty,
    clippy::redundant_clone,
    clippy::inherent_to_string,
    clippy::useless_conversion,
    clippy::unnecessary_to_owned,
    clippy::too_many_arguments,
    clippy::redundant_closure,
    clippy::bool_comparison,
    clippy::while_immutable_condition,
    clippy::identity_op,
    clippy::almost_swapped,
    clippy::needless_borrow,
    clippy::op_ref,
    clippy::iter_overeager_cloned,
    clippy::unnecessary_mut_passed,
    clippy::manual_range_contains,
    clippy::single_match
)]

// Runtime helpers (std/heap/etc.) generated by `homunc --emit-runtime`.
// build.rs writes this into OUT_DIR. Included at crate root so the bare
// function names emitted by `homunc --module` resolve in scope.
include!(concat!(env!("OUT_DIR"), "/runtime.rs"));

// Generated .rs from .hom modules (build.rs compiles src/*.hom -> OUT_DIR).
// Order matters: types first, then the pipeline stages that depend on them.
include!(concat!(env!("OUT_DIR"), "/types.rs"));
include!(concat!(env!("OUT_DIR"), "/lexer.rs"));
include!(concat!(env!("OUT_DIR"), "/parser.rs"));
include!(concat!(env!("OUT_DIR"), "/inline.rs"));
include!(concat!(env!("OUT_DIR"), "/table.rs"));
include!(concat!(env!("OUT_DIR"), "/codegen.rs"));

/// The conversion pipeline: lex → parse blocks → resolve inline → tables → emit.
fn convert_impl(input: &str) -> String {
    let tokens = tokenize(input.to_string());
    let blocks = parse_blocks(tokens);
    let blocks = process_inline(blocks);
    let blocks = parse_tables(blocks);
    render_html(blocks)
}

/// Convert Markdown text to HTML.
#[cfg(not(feature = "wasm"))]
pub fn convert(input: &str) -> String {
    convert_impl(input)
}

#[cfg(feature = "wasm")]
use wasm_bindgen::prelude::*;

/// Convert Markdown text to HTML (wasm-bound).
#[cfg(feature = "wasm")]
#[wasm_bindgen]
pub fn convert(input: &str) -> String {
    convert_impl(input)
}
